executors:
  node:
    docker:
      - image: cimg/node:<< parameters.version >>
    parameters:
      version:
        default: 12.18.3
        type: string
jobs:
  bootstrap:
    executor: node
    parameters:
      concurrency:
        default: 2
        type: integer
    steps:
      - checkout
      - run: ./scripts/assert-changed-files.sh "packages/*|(e2e|integration)-tests/*|.circleci/*"
      - restore_cache:
          key: yarn-offline-cache-v0.0
      - restore_cache:
          key: monorepo-alldeppssssss-v0.0
      - node/install-packages:
          cache-name: monorepo-depsssssssssssssss
          cache-path: ~/.cache/
          cache-version: v2
          pkg-manager: yarn
          with-cache: false
      - save_cache:
          key: monorepo-alldeppssssss-v0.0
          paths:
            - node_modules
            - babel-plugin-remove-graphql-queries/node_modules
            - babel-preset-gatsby-package/node_modules
            - babel-preset-gatsby/node_modules
            - gatsby-admin/node_modules
            - gatsby-cli/node_modules
            - gatsby-codemods/node_modules
            - gatsby-core-utils/node_modules
            - gatsby-cypress/node_modules
            - gatsby-design-tokens/node_modules
            - gatsby-dev-cli/node_modules
            - gatsby-graphiql-explorer/node_modules
            - gatsby-image/node_modules
            - gatsby-legacy-polyfills/node_modules
            - gatsby-link/node_modules
            - gatsby-page-utils/node_modules
            - gatsby-plugin-benchmark-reporting/node_modules
            - gatsby-plugin-canonical-urls/node_modules
            - gatsby-plugin-catch-links/node_modules
            - gatsby-plugin-coffeescript/node_modules
            - gatsby-plugin-create-client-paths/node_modules
            - gatsby-plugin-cxs/node_modules
            - gatsby-plugin-emotion/node_modules
            - gatsby-plugin-facebook-analytics/node_modules
            - gatsby-plugin-feed/node_modules
            - gatsby-plugin-flow/node_modules
            - gatsby-plugin-fullstory/node_modules
            - gatsby-plugin-glamor/node_modules
            - gatsby-plugin-google-analytics/node_modules
            - gatsby-plugin-google-gtag/node_modules
            - gatsby-plugin-google-tagmanager/node_modules
            - gatsby-plugin-guess-js/node_modules
            - gatsby-plugin-jss/node_modules
            - gatsby-plugin-layout/node_modules
            - gatsby-plugin-less/node_modules
            - gatsby-plugin-lodash/node_modules
            - gatsby-plugin-manifest/node_modules
            - gatsby-plugin-mdx/node_modules
            - gatsby-plugin-netlify-cms/node_modules
            - gatsby-plugin-netlify/node_modules
            - gatsby-plugin-no-sourcemaps/node_modules
            - gatsby-plugin-nprogress/node_modules
            - gatsby-plugin-offline/node_modules
            - gatsby-plugin-page-creator/node_modules
            - gatsby-plugin-postcss/node_modules
            - gatsby-plugin-preact/node_modules
            - gatsby-plugin-preload-fonts/node_modules
            - gatsby-plugin-react-css-modules/node_modules
            - gatsby-plugin-react-helmet/node_modules
            - gatsby-plugin-remove-trailing-slashes/node_modules
            - gatsby-plugin-sass/node_modules
            - gatsby-plugin-schema-snapshot/node_modules
            - gatsby-plugin-sharp/node_modules
            - gatsby-plugin-sitemap/node_modules
            - gatsby-plugin-styled-components/node_modules
            - gatsby-plugin-styled-jsx/node_modules
            - gatsby-plugin-styletron/node_modules
            - gatsby-plugin-stylus/node_modules
            - gatsby-plugin-subfont/node_modules
            - gatsby-plugin-twitter/node_modules
            - gatsby-plugin-typescript/node_modules
            - gatsby-plugin-typography/node_modules
            - gatsby-react-router-scroll/node_modules
            - gatsby-recipes/node_modules
            - gatsby-remark-autolink-headers/node_modules
            - gatsby-remark-code-repls/node_modules
            - gatsby-remark-copy-linked-files/node_modules
            - gatsby-remark-custom-blocks/node_modules
            - gatsby-remark-embed-snippet/node_modules
            - gatsby-remark-graphviz/node_modules
            - gatsby-remark-images-contentful/node_modules
            - gatsby-remark-images/node_modules
            - gatsby-remark-katex/node_modules
            - gatsby-remark-prismjs/node_modules
            - gatsby-remark-responsive-iframe/node_modules
            - gatsby-remark-smartypants/node_modules
            - gatsby-source-contentful/node_modules
            - gatsby-source-drupal/node_modules
            - gatsby-source-faker/node_modules
            - gatsby-source-filesystem/node_modules
            - gatsby-source-graphql/node_modules
            - gatsby-source-hacker-news/node_modules
            - gatsby-source-lever/node_modules
            - gatsby-source-medium/node_modules
            - gatsby-source-mongodb/node_modules
            - gatsby-source-npm-package-search/node_modules
            - gatsby-source-shopify/node_modules
            - gatsby-source-wikipedia/node_modules
            - gatsby-source-wordpress/node_modules
            - gatsby-telemetry/node_modules
            - gatsby-theme/node_modules
            - gatsby-transformer-asciidoc/node_modules
            - gatsby-transformer-csv/node_modules
            - gatsby-transformer-documentationjs/node_modules
            - gatsby-transformer-excel/node_modules
            - gatsby-transformer-hjson/node_modules
            - gatsby-transformer-javascript-frontmatter/node_modules
            - gatsby-transformer-javascript-static-exports/node_modules
            - gatsby-transformer-json/node_modules
            - gatsby-transformer-pdf/node_modules
            - gatsby-transformer-react-docgen/node_modules
            - gatsby-transformer-remark/node_modules
            - gatsby-transformer-screenshot/node_modules
            - gatsby-transformer-sharp/node_modules
            - gatsby-transformer-sqip/node_modules
            - gatsby-transformer-toml/node_modules
            - gatsby-transformer-xml/node_modules
            - gatsby-transformer-yaml/node_modules
            - gatsby/node_modules
      - save_cache:
          key: yarn-offline-cache-v0.0
          paths:
            - ./.yarn/yarn-offline-cache/
      - run:
          command: yarn bootstrap -- concurrency=<< parameters.concurrency >> --stream
          name: Build monorepo
      - persist_to_workspace:
          paths:
            - packages/
            - node_modules
          root: ./
  lint:
    executor: node
    parameters:
      concurrency:
        default: 2
        type: integer
    steps:
      - checkout
      - run:
          command: |
            sed -i ':a;N;$!ba;s/,\n\s*"workspaces":\s\[[^]]*]//g' package.json
          name: remove workspaces from package.json
      - node/install-packages:
          cache-name: no-workspace
          cache-path: ~/.cache
          pkg-manager: yarn
      - run: yarn npm-run-all -p lint:code lint:docs lint:other --aggregate-output --max-parallel=<< parameters.concurrency >>
  linux_unit_tests:
    executor:
      name: node
      version: <<parameters.version>>
    parallelism: 4
    parameters:
      version:
        description: node version
        type: string
    steps:
      - checkout
      - run: ./scripts/assert-changed-files.sh "packages/*|.circleci/*"
      - attach_workspace:
          at: ./
      - run:
          command: yarn jest --ci --runInBand $(yarn jest --listTests | circleci tests split --split-by=timings)
          environment:
            GENERATE_JEST_REPORT: true
            JEST_JUNIT_OUTPUT_DIR: ./test-results/jest-node/
            JEST_JUNIT_OUTPUT_NAME: results.xml
            NODE_OPTIONS: --max-old-space-size=2048
          name: Run tests
      - store_test_results:
          path: ./test-results/jest-node/
  typecheck:
    executor: node
    steps:
      - checkout
      - run: ./scripts/assert-changed-files.sh "packages/*|.circleci/*"
      - attach_workspace:
          at: ./
      - run: yarn typecheck
      - run: yarn check-repo-fields
  windows_unit_tests:
    executor:
      name: win/default
    parallelism: 4
    steps:
      - checkout
      - run:
          command: ./scripts/assert-changed-files.sh "packages/*|.circleci/*"
          shell: bash.exe
      - attach_workspace:
          at: ./
      - restore_cache:
          key: yarn-offline-cache-v0.0
      - run: yarn --frozen-lockfile --prefer-offline
      - save_cache:
          key: yarn-offline-cache-v0.0
          paths:
            - ./.yarn/yarn-offline-cache/
      - run:
          command: yarn jest --ci --runInBand $(circleci tests glob "packages/*" | circleci tests split --split-by=timings)
          environment:
            GENERATE_JEST_REPORT: true
            JEST_JUNIT_OUTPUT_DIR: ./test-results/jest-node/
            JEST_JUNIT_OUTPUT_NAME: results.xml
            NODE_OPTIONS: --max-old-space-size=2048
          name: Run tests
      - store_test_results:
          path: ./test-results/jest-node/
orbs:
  node:
    commands:
      install-packages:
        description: |
          Install your Node packages with automated caching and best practices applied.
        parameters:
          app-dir:
            default: ~/project
            description: Path to the directory containing your package.json file. Not needed if package.json lives in the root.
            type: string
          cache-name:
            default: node-deps
            description: the name of the cache, by default it's node-deps.
            type: string
          cache-path:
            default: node-deps
            description: |
              By default, this orb will utilize 'npm ci' and cache the '~/.npm' directory. Override which path to cache with this parameter.
            type: string
          cache-version:
            default: v1
            description: Change the default cache version if you need to clear the cache for any reason.
            type: string
          include-branch-in-cache-key:
            default: true
            description: |
              If true, this cache bucket will only apply to jobs within the same branch.
            type: boolean
          override-ci-command:
            default: ""
            description: |
              By default, packages will be installed with "npm ci" or "yarn install --frozen-lockfile".
              Optionally supply a custom package installation command, with any additional flags needed.
            type: string
          pkg-manager:
            default: npm
            description: Select the default node package manager to use.
            enum:
              - npm
              - yarn
            type: enum
          with-cache:
            default: true
            description: Cache your node packages automatically for faster install times.
            type: boolean
        steps:
          - run:
              command: |
                if [ ! -f "package.json" ]; then
                  echo
                  echo "---"
                  echo "Unable to find your package.json file. Did you forget to set the app-dir parameter?"
                  echo "---"
                  echo
                  echo "Current directory: $(pwd)"
                  echo
                  echo
                  echo "List directory: "
                  echo
                  ls
                  exit 1
                fi
              name: Checking for package.json.
              working_directory: <<parameters.app-dir>>
          - when:
              condition:
                equal:
                  - npm
                  - << parameters.pkg-manager >>
              steps:
                - when:
                    condition: << parameters.with-cache >>
                    steps:
                      - restore_cache:
                          keys:
                            - <<parameters.cache-name>>-<<parameters.cache-version>>-<<#parameters.include-branch-in-cache-key>>{{ .Branch }}-<</parameters.include-branch-in-cache-key>>{{ checksum "<<parameters.app-dir>>/package-lock.json" }}
                - run:
                    command: |
                      if [[ ! -z "<< parameters.override-ci-command >>" ]]; then
                        echo "Running override package installation command:"
                        << parameters.override-ci-command >>
                      else
                        npm ci
                      fi
                    name: Installing NPM packages
                    working_directory: <<parameters.app-dir>>
                - when:
                    condition: << parameters.with-cache >>
                    steps:
                      - when:
                          condition: << parameters.cache-path >>
                          steps:
                            - save_cache:
                                key: <<parameters.cache-name>>-<<parameters.cache-version>>-<<#parameters.include-branch-in-cache-key>>{{ .Branch }}-<</parameters.include-branch-in-cache-key>>{{ checksum "<<parameters.app-dir>>/package-lock.json" }}
                                paths:
                                  - <<parameters.cache-path>>
                      - unless:
                          condition: << parameters.cache-path >>
                          steps:
                            - save_cache:
                                key: <<parameters.cache-name>>-<<parameters.cache-version>>-<<#parameters.include-branch-in-cache-key>>{{ .Branch }}-<</parameters.include-branch-in-cache-key>>{{ checksum "<<parameters.app-dir>>/package-lock.json" }}
                                paths:
                                  - ~/.npm
          - when:
              condition:
                equal:
                  - yarn
                  - << parameters.pkg-manager >>
              steps:
                - when:
                    condition: << parameters.with-cache >>
                    steps:
                      - restore_cache:
                          keys:
                            - <<parameters.cache-name>>-<<parameters.cache-version>>-<<#parameters.include-branch-in-cache-key>>{{ .Branch }}-<</parameters.include-branch-in-cache-key>>{{ checksum "<<parameters.app-dir>>/yarn.lock" }}
                - run:
                    command: |
                      if [[ ! -z "<< parameters.override-ci-command >>" ]]; then
                        echo "Running override package installation command:"
                        << parameters.override-ci-command >>
                      else
                        yarn install --frozen-lockfile --prefer-offline
                      fi
                    name: Installing YARN packages
                    working_directory: <<parameters.app-dir>>
                - when:
                    condition: << parameters.with-cache >>
                    steps:
                      - when:
                          condition: << parameters.cache-path >>
                          steps:
                            - save_cache:
                                key: <<parameters.cache-name>>-<<parameters.cache-version>>-<<#parameters.include-branch-in-cache-key>>{{ .Branch }}-<</parameters.include-branch-in-cache-key>>{{ checksum "<<parameters.app-dir>>/yarn.lock" }}
                                paths:
                                  - <<parameters.cache-path>>
                      - unless:
                          condition: << parameters.cache-path >>
                          steps:
                            - save_cache:
                                key: <<parameters.cache-name>>-<<parameters.cache-version>>-<<#parameters.include-branch-in-cache-key>>{{ .Branch }}-<</parameters.include-branch-in-cache-key>>{{ checksum "<<parameters.app-dir>>/yarn.lock" }}
                                paths:
                                  - <<parameters.app-dir>>/node_modules
    executors:
      default:
        description: |
          Select the version of NodeJS to use. Uses CircleCI's highly cached convenience images built for CI.
          Any available tag from this list can be used: https://hub.docker.com/r/cimg/node/tags
        docker:
          - image: cimg/node:<<parameters.tag>>
        parameters:
          tag:
            default: lts
            description: |
              Pick a specific cimg/node image version tag: https://hub.docker.com/r/cimg/node
            type: string
  slack: circleci/slack@3.4.1
  win: circleci/windows@2.2.0
version: 2.1
workflows:
  build-test:
    jobs:
      - bootstrap
      - lint
      - typecheck:
          requires:
            - bootstrap
      - linux_unit_tests:
          name: unit_tests_node10
          requires:
            - lint
            - typecheck
          version: 10.14.2
      - linux_unit_tests:
          name: unit_tests_node12
          requires:
            - lint
            - typecheck
          version: "12.18"
      - windows_unit_tests:
          name: windows_unit_tests_node
          requires:
            - lint
            - typecheck
